# Generated by Django 4.2.20 on 2025-03-31 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_insert_zipcode_data'),
    ]

    operations = [
    ]
