# Generated by Django 4.2.20 on 2025-03-31 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20250331_1156'),
    ]

    operations = [
    ]
