# Generated by Django 4.2.20 on 2025-04-22 03:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0006_auto_20250331_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='JuniorEmployee',
            fields=[
                ('id', models.IntegerField(db_column='employee_id', primary_key=True, serialize=False)),
                ('first_name', models.CharField(db_column='employee_first_name', max_length=50)),
                ('last_name', models.CharField(db_column='employee_last_name', max_length=50)),
            ],
            options={
                'db_table': 'junior_employee_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_post_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
