# Generated by Django 4.2.20 on 2025-03-31 04:42

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager

def create_initial_category(apps, schema_editor):
    Category = apps.get_model("blog", "Category")
    
    is_existed = Category.objects.filter(pk=1).exists()
    
    if is_existed is False:
        Category.objects.create(name="inital", pk=1)


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_managers_post_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RunPython(create_initial_category, migrations.RunPython.noop),
        migrations.AddField(
            model_name='post',
            name='categoty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.category'),
            preserve_default=False,
        ),
    ]
