# Generated by Django 4.2.20 on 2025-04-15 07:39

import core.model_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_accesslog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('is_public_ch', models.CharField(choices=[('Y', '예'), ('N', '아니오')], default='N', max_length=1)),
                ('is_public_yn', core.model_fields.BooleanYNField(default=False, max_length=1)),
            ],
        ),
    ]
