# Generated by Django 4.2.20 on 2025-04-25 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_posttagrelation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tag_set',
        ),
    ]
